app = "orbdent-people2025"
primary_region = "ams"  # Adjust to your region (e.g., lax)

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "data"
  destination = "/data"

[[statics]]
  guest_path = "/app/frontend/dist"
  url_prefix = "/"
