app = "orbdent-people2025"
primary_region = "ams"  # Adjust to your preferred region

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python", "gcr.io/paketo-buildpacks/nodejs"]

[env]
  PORT = "8000"
  SQLALCHEMY_DATABASE_URL = "postgresql://orbdeqio_user_people:*4A6jds.egXF@<your-fly-postgres-host>:5432/orbdeqio_people"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[statics]]
  guest_path = "/app/frontend/dist"
  url_prefix = "/"
